---
# yaml 파일을 쪼개고, 합치는 것으로 정리해서 local용과 deployment용을 나눌 수 있을 듯
- hosts: all                                            # hosts 파일에 있는 인벤토리 기반으로 실행
  tasks:                                                # 실행할 Task들을 지정

  - name: Node 설치 확인
    command: "node --version"
    register: node
    ignore_errors: yes

  - name: "npm Repo Script 실행"
    script: npm.sh
    when: node.rc == 2

  - name: "Node.js 설치"
    apt: name=nodejs

  - name: "Gulp 설치"
    command: npm install -g gulp
